import type { NicheConfig } from "./types"

export const electricianConfig: NicheConfig = {
  slug: "electrician",
  industryName: "Electrician",
  cardTagline: "Websites for Electrical Contractors",
  cardDescription: "Attract more local jobs with a high-converting site built specifically for electrical contractors and trade businesses.",
  themeClass: "theme-electrician",
  logoSrc: "/addstrategic_banner.png",
  logoAlt: "ADDSTRATEGIC",
  heroImageSrc: "/assets/results/addnexo-hero.png",
  heroImageAlt: "Professional electrician website design example",
  phoneNumber: "+18005550100",
  phoneDisplay: "CALL 800-555-0100",
  ctaUrl: "#contact",
  bookCallUrl: "#contact",
  trustBadges: [
    { src: "/assets/sponsors/L1.png", alt: "Trusted partner badge", width: 80, height: 40 },
    { src: "/assets/sponsors/L2.png", alt: "Industry recognition badge", width: 80, height: 40 },
    { src: "/assets/sponsors/L3.png", alt: "Quality assurance badge", width: 80, height: 40 },
    { src: "/assets/sponsors/L4.png", alt: "Customer rating badge", width: 80, height: 40 },
    { src: "/assets/sponsors/L5.png", alt: "Business excellence badge", width: 80, height: 40 },
    { src: "/assets/sponsors/L6.png", alt: "Service quality badge", width: 80, height: 40 },
  ],
  statCards: [
    { value: "97%", labelIndex: 0 },
    { value: "1,500,000+", labelIndex: 1 },
    { value: "150+", labelIndex: 2 },
  ],
  navLinks: [
    { labelKey: "home", href: "#hero" },
    { labelKey: "industries", href: "#why" },
    { labelKey: "testimonials", href: "#testimonials" },
    { labelKey: "about", href: "#explainer" },
  ],
  servicesDropdown: [
    { labelKey: "webDesign", href: "#split-intro" },
    { labelKey: "seo", href: "#why" },
    { labelKey: "ppc", href: "#explainer" },
  ],
  footerLinks: [
    { labelKey: "services", href: "#split-intro" },
    { labelKey: "why", href: "#why" },
    { labelKey: "testimonials", href: "#testimonials" },
    { labelKey: "contact", href: "#contact" },
    { labelKey: "privacy", href: "/privacy" },
    { labelKey: "terms", href: "/terms" },
  ],
  socialLinks: {
    facebook: "https://www.facebook.com/profile.php?id=61555157255389",
    instagram: "https://www.instagram.com/addstrategic/",
  },
  splitIntroImage: "/assets/results/addnexo-hero.png",
  splitIntroImageAlt: "Website design for electrical companies",
  explainerImage: "/assets/process/web/wireframe-preview.webp",
  explainerImageAlt: "Website design workspace",
  contactImage: "/assets/process/web/reviews.webp",
  contactImageAlt: "Professional workspace for electrician website design consultation",
  reviews: [
    { name: "Dayton R.", rating: 5, role: "Owner, R&R Electric", textIndex: 0 },
    { name: "Maria L.", rating: 5, role: "Operations Manager", textIndex: 1 },
    { name: "James K.", rating: 5, role: "Founder, VoltPro", textIndex: 2 },
    { name: "Samantha T.", rating: 5, role: "Marketing Lead", textIndex: 3 },
  ],
}
